/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BankAccountDto { 
    beneficiaryAccountNumber?: string;
    beneficiaryBankName?: string;
    beneficiaryName?: string;
    beneficiaryPhone?: string;
    iban?: string;
    intermediateBank?: string;
    swiftCode?: string;
}
