/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CurrencyIdDto } from './currencyIdDto';
import { ItemPaymentTermIdDto } from './itemPaymentTermIdDto';
import { UomDto } from './uomDto';


export interface InquiryVersionPricesDto { 
    currency?: CurrencyIdDto;
    inquiryPriceId: number;
    itemPaymentTerm?: ItemPaymentTermIdDto;
    quantity?: number;
    unitPrice?: number;
    uom?: UomDto;
}
