/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InquiryIdDto } from './inquiryIdDto';
import { InquiryVersionPricesDto } from './inquiryVersionPricesDto';
import { InquiryVersionSupplimentDto } from './inquiryVersionSupplimentDto';
import { ItemIncotermIdDto } from './itemIncotermIdDto';
import { ItemSampleTypeDto } from './itemSampleTypeDto';
import { OriginIdDto } from './originIdDto';
import { TransportationDto } from './transportationDto';
import { UomDto } from './uomDto';


export interface InquiryCreationRequestDto { 
    appearance?: string;
    application?: string;
    dissolutionRate?: string;
    escherichiaColi?: string;
    expiryDate?: string;
    extraComment?: string;
    form?: string;
    heavyMetal?: string;
    indotoxinTest?: string;
    injection?: boolean;
    inquiry?: InquiryIdDto;
    inquiryVerrsionPrices?: Array<InquiryVersionPricesDto>;
    inquiryVersionSuppliments?: Array<InquiryVersionSupplimentDto>;
    itemId: number;
    itemIncoterm?: ItemIncotermIdDto;
    itemSampleType?: ItemSampleTypeDto;
    lossOnDrying?: number;
    meltingRange?: number;
    micronization?: boolean;
    molFormula?: string;
    opticalRotation?: number;
    origin?: OriginIdDto;
    packaging?: string;
    particleSize?: number;
    ph?: number;
    portOfDestination?: string;
    purity?: string;
    relatedSubstance?: string;
    residualSolvents?: number;
    residueIgnition?: number;
    salmonelaSpecies?: string;
    sampleSize?: number;
    sampleUnit?: UomDto;
    storage?: string;
    totalVac?: string;
    totalYamc?: string;
    transportation?: TransportationDto;
}
