/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InquiryIdDto } from './inquiryIdDto';
import { InquiryVersionPricesDto } from './inquiryVersionPricesDto';
import { InquiryVersionSupplimentDto } from './inquiryVersionSupplimentDto';
import { ItemIncotermIdDto } from './itemIncotermIdDto';
import { ItemSampleTypeDto } from './itemSampleTypeDto';
import { OriginIdDto } from './originIdDto';
import { TransportationDto } from './transportationDto';
import { UomDto } from './uomDto';


export interface InquiryVersionResponseDto { 
    appearance?: string;
    application?: string;
    changedAttributes?: string;
    dissolutionRate?: string;
    escherichiaColi?: string;
    expiryDate?: Date;
    extraComment?: string;
    form?: string;
    heavyMetal?: string;
    indotoxinTest?: string;
    injection?: boolean;
    inquiry?: InquiryIdDto;
    inquiryVersionId?: number;
    inquiryVersionNumber?: number;
    inquiryVersionPrices?: Array<InquiryVersionPricesDto>;
    inquiryVersionSuppliments?: Array<InquiryVersionSupplimentDto>;
    itemIncoterm?: ItemIncotermIdDto;
    itemSampleType?: ItemSampleTypeDto;
    lossOnDrying?: number;
    meltingRange?: number;
    micronization?: boolean;
    molFormula?: string;
    opticalRotation?: number;
    origin?: OriginIdDto;
    packaging?: string;
    particleSize?: number;
    ph?: number;
    portOfDestination?: string;
    purity?: string;
    relatedSubstance?: string;
    residualSolvents?: number;
    residueIgnition?: number;
    salmonelaSpecies?: string;
    sampleSize?: number;
    sampleUnit?: UomDto;
    status?: InquiryVersionResponseDto.StatusEnum;
    storage?: string;
    totalVac?: string;
    totalYamc?: string;
    transportation?: TransportationDto;
}
export namespace InquiryVersionResponseDto {
    export type StatusEnum = 'ACCEPTED' | 'CANCELED' | 'CREATED' | 'SUPPLIER_DRAFTED' | 'SUPPLIER_MODIFIED' | 'USER_DRAFTED' | 'USER_MODIFIED';
    export const StatusEnum = {
        ACCEPTED: 'ACCEPTED' as StatusEnum,
        CANCELED: 'CANCELED' as StatusEnum,
        CREATED: 'CREATED' as StatusEnum,
        SUPPLIERDRAFTED: 'SUPPLIER_DRAFTED' as StatusEnum,
        SUPPLIERMODIFIED: 'SUPPLIER_MODIFIED' as StatusEnum,
        USERDRAFTED: 'USER_DRAFTED' as StatusEnum,
        USERMODIFIED: 'USER_MODIFIED' as StatusEnum
    };
}
