/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ItemSearchFilter { 
    caseNumber?: string;
    coa?: boolean;
    dmf?: boolean;
    gmpCertificate?: boolean;
    halal?: boolean;
    injection?: boolean;
    iso?: boolean;
    itemCategoryId?: number;
    itemName?: string;
    itemSampleTypesId?: number;
    itemSubcategoryId?: number;
    originId?: number;
    particleSize?: string;
    purity?: string;
    supplierTypeId?: number;
}
