/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttachmentDto } from './attachmentDto';
import { ItemCategoryIdDto } from './itemCategoryIdDto';
import { ItemCertificateDto } from './itemCertificateDto';
import { ItemKeywordDto } from './itemKeywordDto';
import { ItemPricingDto } from './itemPricingDto';
import { ItemSubcategoryIdDto } from './itemSubcategoryIdDto';
import { ItemSupplimentDto } from './itemSupplimentDto';
import { OriginIdDto } from './originIdDto';
import { SupplierIdDto } from './supplierIdDto';


export interface ItemDraftDto { 
    advantage?: string;
    appearence?: string;
    application?: string;
    attachment?: AttachmentDto;
    caseNumber?: string;
    coa?: string;
    commercialQuantity?: number;
    creationDate?: Date;
    details?: string;
    dissolutionRate?: string;
    dmf?: string;
    escherichiaColi?: string;
    expiryDate?: Date;
    form?: string;
    freeSamplePaidShippingQuantity?: number;
    freeSampleShippingQuantity?: number;
    gmpCertificate?: string;
    halal?: string;
    heavyMetal?: string;
    indotoxinTest?: string;
    injection?: boolean;
    iso?: string;
    itemCategory?: ItemCategoryIdDto;
    itemCertificates?: Array<ItemCertificateDto>;
    itemId?: number;
    itemKeywords?: Array<ItemKeywordDto>;
    itemName?: string;
    itemPricings?: Array<ItemPricingDto>;
    itemSubcategory?: ItemSubcategoryIdDto;
    itemSuppliments?: Array<ItemSupplimentDto>;
    lossOnDrying?: number;
    meltingRange?: number;
    micronization?: boolean;
    molFormula?: string;
    opticalRotation?: number;
    origin?: OriginIdDto;
    paidSampleQuantity?: number;
    particleSize?: string;
    ph?: number;
    productionCapacity?: string;
    purity?: string;
    relatedSubstance?: string;
    residualSolvents?: number;
    residueIgnition?: number;
    salmonelaSpecies?: string;
    status?: number;
    storage?: string;
    supplier?: SupplierIdDto;
    totalVac?: string;
    totalYamc?: string;
}
