/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CurrencyIdDto } from './currencyIdDto';
import { ItemIdDto } from './itemIdDto';
import { ItemQuotationIdDto } from './itemQuotationIdDto';
import { UomIdDto } from './uomIdDto';
import { UserIdDto } from './userIdDto';


export interface ItemOrderDto { 
    adjustment?: string;
    caseNumber: string;
    creationDate?: Date;
    currency?: CurrencyIdDto;
    dissolutionRate: string;
    expiryDate: Date;
    form?: string;
    heavyMetal: string;
    indotoxinTest?: string;
    injection?: boolean;
    item?: ItemIdDto;
    itemQuotation?: ItemQuotationIdDto;
    lastUpdateDate?: Date;
    lossOnDrying: number;
    meltingRange: number;
    micronization?: boolean;
    orderId?: number;
    particleSize: number;
    ph: number;
    purity: string;
    quantity: number;
    relatedSubstance?: string;
    status: number;
    unitPrice: number;
    uom?: UomIdDto;
    user?: UserIdDto;
}
