/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatUserDto } from './chatUserDto';
import { MessageAttachmentDto } from './messageAttachmentDto';


export interface MessageDto { 
    attachments?: Array<MessageAttachmentDto>;
    messageContent: string;
    messageDateTime?: Date;
    messageId?: number;
    sender?: ChatUserDto;
}
