/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttachmentDto } from './attachmentDto';
import { ChatUserDto } from './chatUserDto';


export interface MessageDto { 
    attachment?: AttachmentDto;
    messageContent: string;
    messageDateTime?: string;
    messageId?: number;
    sender?: ChatUserDto;
}
