/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OriginIdDto } from './originIdDto';


export interface ProfileUserDto { 
    companyLocation?: OriginIdDto;
    companyName?: string;
    firstName?: string;
    lastName?: string;
    userId?: number;
    email?: string;
}
