/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDto } from './addressDto';
import { AttachmentDto } from './attachmentDto';


export interface ProfileUserProfileDto { 
    aboutMe?: string;
    address?: AddressDto;
    fax?: string;
    gender?: number;
    image?: AttachmentDto;
    interestedIn?: string;
    landLine?: string;
    phone?: string;
    skype?: string;
    title?: string;
    userProfileId?: number;
    workingIn?: string;
}
