/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttachmentDto } from './attachmentDto';
import { ItemCategoryIdDto } from './itemCategoryIdDto';
import { ItemKeywordDto } from './itemKeywordDto';
import { ItemSubcategoryIdDto } from './itemSubcategoryIdDto';
import { ItemSupplimentDto } from './itemSupplimentDto';
import { OriginIdDto } from './originIdDto';
import { TransportationDto } from './transportationDto';
import { UomIdDto } from './uomIdDto';


export interface PublicItemDto {
    advantage?: string;
    appearence?: string;
    application: string;
    attachment: AttachmentDto;
    caseNumber: string;
    coa: string;
    commercialQuantity?: number;
    creationDate?: Date;
    details?: string;
    dissolutionRate: string;
    dmf?: string;
    escherichiaColi?: string;
    estimatedDeliveryLeadTime?: string;
    expiryDate: Date;
    form?: string;
    freeSamplePaidShippingQuantity?: number;
    freeSampleShippingQuantity?: number;
    halal?: string;
    heavyMetal: string;
    indotoxinTest?: string;
    injection?: boolean;
    iso?: string;
    itemCategory: ItemCategoryIdDto;
    itemId?: number;
    itemKeywords?: Array<ItemKeywordDto>;
    itemName: string;
    itemSubcategory: ItemSubcategoryIdDto;
    itemSuppliments?: Array<ItemSupplimentDto>;
    lossOnDrying: number;
    meltingRange: number;
    micronization?: boolean;
    minOrderQuantity: number;
    molFormula?: string;
    opticalRotation?: number;
    origin?: OriginIdDto;
    packaging?: string;
    paidSampleQuantity?: number;
    particleSize: string;
    ph: number;
    portOfDispatching?: string;
    productionCapacity?: string;
    purity: string;
    relatedSubstance?: string;
    residualSolvents?: number;
    residueIgnition: number;
    salmonelaSpecies?: string;
    status: number;
    storage: string;
    totalVac?: string;
    totalYamc?: string;
    transportation?: TransportationDto;
    uom: UomIdDto;
}
