/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDto } from './addressDto';
import { AttachmentDto } from './attachmentDto';
import { SupplierCategoryDto } from './supplierCategoryDto';


export interface SupplierDto { 
    address?: AddressDto;
    attachment?: AttachmentDto;
    companyName?: string;
    establishmentDate?: Date;
    exportPercentage?: string;
    mainCustomer?: string;
    numberEmployees?: number;
    phone?: string;
    supplierCategory?: SupplierCategoryDto;
    supplierEmail: string;
    supplierId?: number;
    supplierName: string;
    totalAnnualSales?: string;
    website?: string;
}
