/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttachmentDto } from './attachmentDto';
import { SupplierCategoryDto } from './supplierCategoryDto';


export interface UpdateSupplierSupplierDto { 
    businessLicense?: AttachmentDto;
    companyType?: string;
    establishmentDate?: Date;
    exportPercentage?: string;
    mainCustomer?: string;
    mainMarkets?: string;
    numberEmployees?: number;
    supplierCategory?: SupplierCategoryDto;
    totalAnnualSales?: string;
    website?: string;
}
