/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDto } from './addressDto';
import { AttachmentDto } from './attachmentDto';


export interface UpdateSupplierUserProfileDto { 
    aboutMe?: string;
    address?: AddressDto;
    fax?: string;
    gender?: UpdateSupplierUserProfileDto.GenderEnum;
    interestedIn?: string;
    landline?: string;
    phone?: string;
    photo?: AttachmentDto;
    skype?: string;
    title?: string;
    workingIn?: string;
}
export namespace UpdateSupplierUserProfileDto {
    export type GenderEnum = 'FEMALE' | 'MALE';
    export const GenderEnum = {
        FEMALE: 'FEMALE' as GenderEnum,
        MALE: 'MALE' as GenderEnum
    };
}
