/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDto } from './addressDto';
import { AttachmentDto } from './attachmentDto';
import { CustomerDto } from './customerDto';


export interface UserProfileDto { 
    aboutMe?: string;
    address?: AddressDto;
    attachment?: AttachmentDto;
    companyName?: string;
    customer?: CustomerDto;
    fax?: string;
    gender?: UserProfileDto.GenderEnum;
    interestedIn?: string;
    jobTitle?: string;
    landLine?: string;
    phone?: string;
    skype?: string;
    title?: string;
    userProfileId?: number;
    workingIn?: string;
}
export namespace UserProfileDto {
    export type GenderEnum = 'FEMALE' | 'MALE';
    export const GenderEnum = {
        FEMALE: 'FEMALE' as GenderEnum,
        MALE: 'MALE' as GenderEnum
    };
}
