export * from './inboxController.service';
import { InboxControllerService } from './inboxController.service';
export * from './inquiryController.service';
import { InquiryControllerService } from './inquiryController.service';
export * from './itemCategoryController.service';
import { ItemCategoryControllerService } from './itemCategoryController.service';
export * from './itemController.service';
import { ItemControllerService } from './itemController.service';
export * from './itemOrderController.service';
import { ItemOrderControllerService } from './itemOrderController.service';
export * from './jwtAuthenticationController.service';
import { JwtAuthenticationControllerService } from './jwtAuthenticationController.service';
export * from './lookupController.service';
import { LookupControllerService } from './lookupController.service';
export * from './originController.service';
import { OriginControllerService } from './originController.service';
export * from './publicDataController.service';
import { PublicDataControllerService } from './publicDataController.service';
export * from './quotationController.service';
import { QuotationControllerService } from './quotationController.service';
export * from './registerController.service';
import { RegisterControllerService } from './registerController.service';
export * from './supplierController.service';
import { SupplierControllerService } from './supplierController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [InboxControllerService, InquiryControllerService, ItemCategoryControllerService, ItemControllerService, ItemOrderControllerService, JwtAuthenticationControllerService, LookupControllerService, OriginControllerService, PublicDataControllerService, QuotationControllerService, RegisterControllerService, SupplierControllerService, UserControllerService];
