export * from './accountCancelController.service';
import { AccountCancelControllerService } from './accountCancelController.service';
export * from './eventController.service';
import { EventControllerService } from './eventController.service';
export * from './faqController.service';
import { FaqControllerService } from './faqController.service';
export * from './inboxController.service';
import { InboxControllerService } from './inboxController.service';
export * from './inquiryController.service';
import { InquiryControllerService } from './inquiryController.service';
export * from './itemCategoryController.service';
import { ItemCategoryControllerService } from './itemCategoryController.service';
export * from './itemController.service';
import { ItemControllerService } from './itemController.service';
export * from './jwtAuthenticationController.service';
import { JwtAuthenticationControllerService } from './jwtAuthenticationController.service';
export * from './lookupController.service';
import { LookupControllerService } from './lookupController.service';
export * from './newsController.service';
import { NewsControllerService } from './newsController.service';
export * from './orderController.service';
import { OrderControllerService } from './orderController.service';
export * from './originController.service';
import { OriginControllerService } from './originController.service';
export * from './partnersController.service';
import { PartnersControllerService } from './partnersController.service';
export * from './publicDataController.service';
import { PublicDataControllerService } from './publicDataController.service';
export * from './quotationController.service';
import { QuotationControllerService } from './quotationController.service';
export * from './registerController.service';
import { RegisterControllerService } from './registerController.service';
export * from './supplierController.service';
import { SupplierControllerService } from './supplierController.service';
export * from './supplierEmployeeController.service';
import { SupplierEmployeeControllerService } from './supplierEmployeeController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AccountCancelControllerService, EventControllerService, FaqControllerService, InboxControllerService, InquiryControllerService, ItemCategoryControllerService, ItemControllerService, JwtAuthenticationControllerService, LookupControllerService, NewsControllerService, OrderControllerService, OriginControllerService, PartnersControllerService, PublicDataControllerService, QuotationControllerService, RegisterControllerService, SupplierControllerService, SupplierEmployeeControllerService, UserControllerService];
