/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DealDto } from '../model/dealDto';
import { InvoiceDto } from '../model/invoiceDto';
import { OrderDto } from '../model/orderDto';
import { PageDealDto } from '../model/pageDealDto';
import { QuotationResponseDto } from '../model/quotationResponseDto';
import { ViewInquiryMainDataDto } from '../model/viewInquiryMainDataDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DealControllerService {

    protected basePath = 'https://164.92.242.241:8060';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * this api is responsiable for get deal by deal id
     * 
     * @param dealId dealId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDealByDealIdUsingGET(dealId: number, observe?: 'body', reportProgress?: boolean): Observable<DealDto>;
    public getDealByDealIdUsingGET(dealId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DealDto>>;
    public getDealByDealIdUsingGET(dealId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DealDto>>;
    public getDealByDealIdUsingGET(dealId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (dealId === null || dealId === undefined) {
            throw new Error('Required parameter dealId was null or undefined when calling getDealByDealIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DealDto>(`${this.basePath}/api/deals/${encodeURIComponent(String(dealId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * this api is responsiable for list all deals for logging customer 
     * 
     * @param dealStatus dealStatus
     * @param page page
     * @param size size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDealsForCustomerUsingGET(dealStatus?: number, page?: number, size?: number, observe?: 'body', reportProgress?: boolean): Observable<PageDealDto>;
    public getDealsForCustomerUsingGET(dealStatus?: number, page?: number, size?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PageDealDto>>;
    public getDealsForCustomerUsingGET(dealStatus?: number, page?: number, size?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PageDealDto>>;
    public getDealsForCustomerUsingGET(dealStatus?: number, page?: number, size?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (dealStatus !== undefined && dealStatus !== null) {
            queryParameters = queryParameters.set('dealStatus', <any>dealStatus);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters = queryParameters.set('size', <any>size);
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<PageDealDto>(`${this.basePath}/api/deals/customer`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * this api is responsiable for list all deals for logging supplier 
     * 
     * @param dealStatus dealStatus
     * @param page page
     * @param size size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDealsForSupplierUsingGET(dealStatus?: number, page?: number, size?: number, observe?: 'body', reportProgress?: boolean): Observable<PageDealDto>;
    public getDealsForSupplierUsingGET(dealStatus?: number, page?: number, size?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PageDealDto>>;
    public getDealsForSupplierUsingGET(dealStatus?: number, page?: number, size?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PageDealDto>>;
    public getDealsForSupplierUsingGET(dealStatus?: number, page?: number, size?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (dealStatus !== undefined && dealStatus !== null) {
            queryParameters = queryParameters.set('dealStatus', <any>dealStatus);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters = queryParameters.set('size', <any>size);
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<PageDealDto>(`${this.basePath}/api/deals/supplier`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get inquiry for deal by dealId
     * 
     * @param dealId dealId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getInquiryByDealIdUsingGET(dealId: number, observe?: 'body', reportProgress?: boolean): Observable<ViewInquiryMainDataDto>;
    public getInquiryByDealIdUsingGET(dealId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ViewInquiryMainDataDto>>;
    public getInquiryByDealIdUsingGET(dealId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ViewInquiryMainDataDto>>;
    public getInquiryByDealIdUsingGET(dealId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (dealId === null || dealId === undefined) {
            throw new Error('Required parameter dealId was null or undefined when calling getInquiryByDealIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ViewInquiryMainDataDto>(`${this.basePath}/api/deals/inquiry/${encodeURIComponent(String(dealId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get invoice for deal by dealId
     * 
     * @param dealId dealId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getInvocieByDealIdUsingGET(dealId: number, observe?: 'body', reportProgress?: boolean): Observable<InvoiceDto>;
    public getInvocieByDealIdUsingGET(dealId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InvoiceDto>>;
    public getInvocieByDealIdUsingGET(dealId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InvoiceDto>>;
    public getInvocieByDealIdUsingGET(dealId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (dealId === null || dealId === undefined) {
            throw new Error('Required parameter dealId was null or undefined when calling getInvocieByDealIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<InvoiceDto>(`${this.basePath}/api/deals/invoice/${encodeURIComponent(String(dealId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get ordr for deal by dealId
     * 
     * @param dealId dealId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOrderByDealIdUsingGET(dealId: number, observe?: 'body', reportProgress?: boolean): Observable<OrderDto>;
    public getOrderByDealIdUsingGET(dealId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OrderDto>>;
    public getOrderByDealIdUsingGET(dealId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OrderDto>>;
    public getOrderByDealIdUsingGET(dealId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (dealId === null || dealId === undefined) {
            throw new Error('Required parameter dealId was null or undefined when calling getOrderByDealIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<OrderDto>(`${this.basePath}/api/deals/order/${encodeURIComponent(String(dealId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get quotation for deal by dealId
     * 
     * @param dealId dealId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getQuotationByIdUsingGET(dealId: number, observe?: 'body', reportProgress?: boolean): Observable<QuotationResponseDto>;
    public getQuotationByIdUsingGET(dealId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<QuotationResponseDto>>;
    public getQuotationByIdUsingGET(dealId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<QuotationResponseDto>>;
    public getQuotationByIdUsingGET(dealId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (dealId === null || dealId === undefined) {
            throw new Error('Required parameter dealId was null or undefined when calling getQuotationByIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<QuotationResponseDto>(`${this.basePath}/api/deals/quotation/${encodeURIComponent(String(dealId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
