/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { InvoiceDto } from '../model/invoiceDto';
import { InvoiceRequestDto } from '../model/invoiceRequestDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class InvoiceControllerService {

    protected basePath = 'https://164.92.242.241:8060';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Accept invoice From customer
     * 
     * @param invoiceId invoiceId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public acceptInvoiceUsingPUT(invoiceId: number, observe?: 'body', reportProgress?: boolean): Observable<InvoiceDto>;
    public acceptInvoiceUsingPUT(invoiceId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InvoiceDto>>;
    public acceptInvoiceUsingPUT(invoiceId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InvoiceDto>>;
    public acceptInvoiceUsingPUT(invoiceId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (invoiceId === null || invoiceId === undefined) {
            throw new Error('Required parameter invoiceId was null or undefined when calling acceptInvoiceUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.put<InvoiceDto>(`${this.basePath}/api/invoice/${encodeURIComponent(String(invoiceId))}/accept`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Add a new invoice about an existing deal.
     * 
     * @param invoiceRequestDto invoiceRequestDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addInvoiceUsingPOST(invoiceRequestDto: InvoiceRequestDto, observe?: 'body', reportProgress?: boolean): Observable<InvoiceDto>;
    public addInvoiceUsingPOST(invoiceRequestDto: InvoiceRequestDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InvoiceDto>>;
    public addInvoiceUsingPOST(invoiceRequestDto: InvoiceRequestDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InvoiceDto>>;
    public addInvoiceUsingPOST(invoiceRequestDto: InvoiceRequestDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (invoiceRequestDto === null || invoiceRequestDto === undefined) {
            throw new Error('Required parameter invoiceRequestDto was null or undefined when calling addInvoiceUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<InvoiceDto>(`${this.basePath}/api/invoice`,
            invoiceRequestDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get accepted invoice by deal id
     * 
     * @param dealId dealId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAcceptedInvoiceUsingGET(dealId: number, observe?: 'body', reportProgress?: boolean): Observable<InvoiceDto>;
    public getAcceptedInvoiceUsingGET(dealId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InvoiceDto>>;
    public getAcceptedInvoiceUsingGET(dealId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InvoiceDto>>;
    public getAcceptedInvoiceUsingGET(dealId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (dealId === null || dealId === undefined) {
            throw new Error('Required parameter dealId was null or undefined when calling getAcceptedInvoiceUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<InvoiceDto>(`${this.basePath}/api/invoice/${encodeURIComponent(String(dealId))}/acceptedInvoice`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get invoice by invoice id
     * 
     * @param invoiceId invoiceId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getInvoiceByIdUsingGET(invoiceId: number, observe?: 'body', reportProgress?: boolean): Observable<InvoiceDto>;
    public getInvoiceByIdUsingGET(invoiceId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InvoiceDto>>;
    public getInvoiceByIdUsingGET(invoiceId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InvoiceDto>>;
    public getInvoiceByIdUsingGET(invoiceId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (invoiceId === null || invoiceId === undefined) {
            throw new Error('Required parameter invoiceId was null or undefined when calling getInvoiceByIdUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<InvoiceDto>(`${this.basePath}/api/invoice/${encodeURIComponent(String(invoiceId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * reject invoice From customer
     * 
     * @param invoiceId invoiceId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public rejectInvoiceUsingPUT(invoiceId: number, observe?: 'body', reportProgress?: boolean): Observable<InvoiceDto>;
    public rejectInvoiceUsingPUT(invoiceId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InvoiceDto>>;
    public rejectInvoiceUsingPUT(invoiceId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InvoiceDto>>;
    public rejectInvoiceUsingPUT(invoiceId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (invoiceId === null || invoiceId === undefined) {
            throw new Error('Required parameter invoiceId was null or undefined when calling rejectInvoiceUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.put<InvoiceDto>(`${this.basePath}/api/invoice/${encodeURIComponent(String(invoiceId))}/reject`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
