/**
 * apis backend
 * Ahmed Abdelrhman & Mohamed sabri
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';
import { AttachmentSource } from '../model/attachmentSource';
import { CertificateTypeDto } from '../model/certificateTypeDto';
import { CityDto } from '../model/cityDto';
import { CurrencyDto } from '../model/currencyDto';
import { DealStepTypeDto } from '../model/dealStepTypeDto';
import { IncotermDto } from '../model/incotermDto';
import { ItemCategoryDto } from '../model/itemCategoryDto';
import { ItemKeywordDto } from '../model/itemKeywordDto';
import { ItemProductionCapacityDto } from '../model/itemProductionCapacityDto';
import { ItemSampleTypeDto } from '../model/itemSampleTypeDto';
import { OriginDto } from '../model/originDto';
import { PaymentTermDto } from '../model/paymentTermDto';
import { ProfileAnnualSalesDto } from '../model/profileAnnualSalesDto';
import { ProfileEmployeesNumberDto } from '../model/profileEmployeesNumberDto';
import { ProfileExportPercentageDto } from '../model/profileExportPercentageDto';
import { ProfileInterestDto } from '../model/profileInterestDto';
import { ProfileMainCustomerDto } from '../model/profileMainCustomerDto';
import { ProfileMainMarketDto } from '../model/profileMainMarketDto';
import { SupplierCategoryDto } from '../model/supplierCategoryDto';
import { TransportationDto } from '../model/transportationDto';
import { UomDto } from '../model/uomDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class LookupControllerService {

    protected basePath = 'https://164.92.242.241:8060';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * this api will get all shipings incoterms in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllIncotermsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<IncotermDto>>;
    public getAllIncotermsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<IncotermDto>>>;
    public getAllIncotermsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<IncotermDto>>>;
    public getAllIncotermsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<IncotermDto>>(`${this.basePath}/lookup/shiping`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * this api will get all payment terms in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPaymentTermsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<PaymentTermDto>>;
    public getAllPaymentTermsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PaymentTermDto>>>;
    public getAllPaymentTermsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PaymentTermDto>>>;
    public getAllPaymentTermsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<PaymentTermDto>>(`${this.basePath}/lookup/payment-terms`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get annual sales volume lookups
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAnnualSalesVolumeUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<ProfileAnnualSalesDto>>;
    public getAnnualSalesVolumeUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ProfileAnnualSalesDto>>>;
    public getAnnualSalesVolumeUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ProfileAnnualSalesDto>>>;
    public getAnnualSalesVolumeUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ProfileAnnualSalesDto>>(`${this.basePath}/lookup/annualSalesVolume`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * This Api will get all attachments source in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAttachmentsSourceUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<AttachmentSource>>;
    public getAttachmentsSourceUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AttachmentSource>>>;
    public getAttachmentsSourceUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AttachmentSource>>>;
    public getAttachmentsSourceUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<AttachmentSource>>(`${this.basePath}/lookup/attachments-source`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get currencies in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCurrenciesUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<CurrencyDto>>;
    public getCurrenciesUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CurrencyDto>>>;
    public getCurrenciesUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CurrencyDto>>>;
    public getCurrenciesUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<CurrencyDto>>(`${this.basePath}/lookup/currency`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deal status lookup
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDealStatuesMapUsingGET(observe?: 'body', reportProgress?: boolean): Observable<{ [key: string]: string; }>;
    public getDealStatuesMapUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<{ [key: string]: string; }>>;
    public getDealStatuesMapUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<{ [key: string]: string; }>>;
    public getDealStatuesMapUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<{ [key: string]: string; }>(`${this.basePath}/lookup/deal-status`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get all deal step types in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDealStepTypesUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<DealStepTypeDto>>;
    public getDealStepTypesUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DealStepTypeDto>>>;
    public getDealStepTypesUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DealStepTypeDto>>>;
    public getDealStepTypesUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<DealStepTypeDto>>(`${this.basePath}/lookup/dealStepTypes`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get employees number lookups
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEmployeesNumberUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<ProfileEmployeesNumberDto>>;
    public getEmployeesNumberUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ProfileEmployeesNumberDto>>>;
    public getEmployeesNumberUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ProfileEmployeesNumberDto>>>;
    public getEmployeesNumberUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ProfileEmployeesNumberDto>>(`${this.basePath}/lookup/employeesNumber`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get all item estiamtion  delivery Period in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEstimationDeliveryUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<string>>;
    public getEstimationDeliveryUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<string>>>;
    public getEstimationDeliveryUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<string>>>;
    public getEstimationDeliveryUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<string>>(`${this.basePath}/lookup/estiamtionDeliveryTime`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get export percentage lookups
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExportPercentageUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<ProfileExportPercentageDto>>;
    public getExportPercentageUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ProfileExportPercentageDto>>>;
    public getExportPercentageUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ProfileExportPercentageDto>>>;
    public getExportPercentageUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ProfileExportPercentageDto>>(`${this.basePath}/lookup/exportPercentage`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Inquiry status lookup
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getInquiryStatuesMapUsingGET(observe?: 'body', reportProgress?: boolean): Observable<{ [key: string]: string; }>;
    public getInquiryStatuesMapUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<{ [key: string]: string; }>>;
    public getInquiryStatuesMapUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<{ [key: string]: string; }>>;
    public getInquiryStatuesMapUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<{ [key: string]: string; }>(`${this.basePath}/lookup/inquiry-status`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get interests lookups
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getInterestsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<ProfileInterestDto>>;
    public getInterestsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ProfileInterestDto>>>;
    public getInterestsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ProfileInterestDto>>>;
    public getInterestsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ProfileInterestDto>>(`${this.basePath}/lookup/interests`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get all item certificate Types in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getItemCerTypeUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<CertificateTypeDto>>;
    public getItemCerTypeUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CertificateTypeDto>>>;
    public getItemCerTypeUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CertificateTypeDto>>>;
    public getItemCerTypeUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<CertificateTypeDto>>(`${this.basePath}/lookup/itemCertificateType`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get all item Prod Capacity in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getItemProdCapacityUsingGET(observe?: 'body', reportProgress?: boolean): Observable<ItemProductionCapacityDto>;
    public getItemProdCapacityUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ItemProductionCapacityDto>>;
    public getItemProdCapacityUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ItemProductionCapacityDto>>;
    public getItemProdCapacityUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ItemProductionCapacityDto>(`${this.basePath}/lookup/productionCapacityInfo`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get item sample types in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getItemSampleTypesUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<ItemSampleTypeDto>>;
    public getItemSampleTypesUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ItemSampleTypeDto>>>;
    public getItemSampleTypesUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ItemSampleTypeDto>>>;
    public getItemSampleTypesUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ItemSampleTypeDto>>(`${this.basePath}/lookup/sampleTypes`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get item status lookups
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getItemStatuesMapUsingGET(observe?: 'body', reportProgress?: boolean): Observable<{ [key: string]: string; }>;
    public getItemStatuesMapUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<{ [key: string]: string; }>>;
    public getItemStatuesMapUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<{ [key: string]: string; }>>;
    public getItemStatuesMapUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<{ [key: string]: string; }>(`${this.basePath}/lookup/itemStatus`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * This Api will get all items category in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getItemsCategoryUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<ItemCategoryDto>>;
    public getItemsCategoryUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ItemCategoryDto>>>;
    public getItemsCategoryUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ItemCategoryDto>>>;
    public getItemsCategoryUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ItemCategoryDto>>(`${this.basePath}/lookup/items-category`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * this api is responsiable for list all keywords for user
     *
     * @param keywordName keywordName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getItemsKeywordsUsingGET(keywordName?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<ItemKeywordDto>>;
    public getItemsKeywordsUsingGET(keywordName?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ItemKeywordDto>>>;
    public getItemsKeywordsUsingGET(keywordName?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ItemKeywordDto>>>;
    public getItemsKeywordsUsingGET(keywordName?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (keywordName !== undefined && keywordName !== null) {
            queryParameters = queryParameters.set('keywordName', <any>keywordName);
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ItemKeywordDto>>(`${this.basePath}/lookup/item-keywords`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get main customer lookups
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMainCustomerUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<ProfileMainCustomerDto>>;
    public getMainCustomerUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ProfileMainCustomerDto>>>;
    public getMainCustomerUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ProfileMainCustomerDto>>>;
    public getMainCustomerUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ProfileMainCustomerDto>>(`${this.basePath}/lookup/mainCustomers`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get main markets lookups
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMainMarketsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<ProfileMainMarketDto>>;
    public getMainMarketsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ProfileMainMarketDto>>>;
    public getMainMarketsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ProfileMainMarketDto>>>;
    public getMainMarketsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ProfileMainMarketDto>>(`${this.basePath}/lookup/mainMarkets`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get country city
     *
     * @param originId originId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOriginCitiesUsingGET(originId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<CityDto>>;
    public getOriginCitiesUsingGET(originId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CityDto>>>;
    public getOriginCitiesUsingGET(originId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CityDto>>>;
    public getOriginCitiesUsingGET(originId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (originId === null || originId === undefined) {
            throw new Error('Required parameter originId was null or undefined when calling getOriginCitiesUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<CityDto>>(`${this.basePath}/lookup/origins/${encodeURIComponent(String(originId))}/cities`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * This Api will get all origin in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOriginsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<OriginDto>>;
    public getOriginsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<OriginDto>>>;
    public getOriginsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<OriginDto>>>;
    public getOriginsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<OriginDto>>(`${this.basePath}/lookup/origins`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get all shipping certificate Types in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getShippingCerTypeUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<CertificateTypeDto>>;
    public getShippingCerTypeUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CertificateTypeDto>>>;
    public getShippingCerTypeUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CertificateTypeDto>>>;
    public getShippingCerTypeUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<CertificateTypeDto>>(`${this.basePath}/lookup/shippingCertificateType`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * This Api will get all supplier Category in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSuppliersCategoryUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<SupplierCategoryDto>>;
    public getSuppliersCategoryUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SupplierCategoryDto>>>;
    public getSuppliersCategoryUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SupplierCategoryDto>>>;
    public getSuppliersCategoryUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<SupplierCategoryDto>>(`${this.basePath}/lookup/suppliers-category`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * get unit of measure (samples unit) in the system
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUnitOfMeasureUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<UomDto>>;
    public getUnitOfMeasureUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<UomDto>>>;
    public getUnitOfMeasureUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<UomDto>>>;
    public getUnitOfMeasureUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<UomDto>>(`${this.basePath}/lookup/uoms`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * this api is responsiable for list all transportation for user
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public gettranspTransportationDtosUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<TransportationDto>>;
    public gettranspTransportationDtosUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TransportationDto>>>;
    public gettranspTransportationDtosUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TransportationDto>>>;
    public gettranspTransportationDtosUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<TransportationDto>>(`${this.basePath}/lookup/transportations`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
